version: '2'

services:
    mysql:
        image: mysql:5.5
        env_file: .env
        volumes:
            - ./data:/var/lib/mysql

    magento:
        image: pagarme/magento:osc
        env_file: .env
        volumes:
            - .:/opt/docker/magento/module/
        working_dir: /var/www
        ports:
            - "80:80"
        depends_on:
            - mysql
